
package student.teacher.portal;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class SignIn extends javax.swing.JFrame {

    /**
     * Creates new form SignIn
     */
    private static Admin admin;

    
    public SignIn() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("images/icons8_Student_Male_50px.png")));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setResizable(false);
        setTitle("Student Teacher Portal");
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LeftPanel = new javax.swing.JPanel();
        Image = new javax.swing.JLabel();
        Title = new javax.swing.JLabel();
        Description = new javax.swing.JLabel();
        RightPanel = new javax.swing.JPanel();
        LBL_Username = new javax.swing.JLabel();
        TF_Username = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        LBL_Password = new javax.swing.JLabel();
        PF_Password = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        BTN_SignIn = new javax.swing.JButton();
        BTN_Close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        LeftPanel.setBackground(new java.awt.Color(13, 56, 247));

        Image.setForeground(new java.awt.Color(255, 255, 255));
        Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/teacher/portal/images/Education_100px.png"))); // NOI18N

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 255, 255));
        Title.setText("Student Teacher Portal");

        Description.setBackground(new java.awt.Color(255, 255, 255));
        Description.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        Description.setForeground(new java.awt.Color(255, 255, 255));
        Description.setText("Create and Manage Courses");

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(Image))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(Title))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Description)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(Image)
                .addGap(51, 51, 51)
                .addComponent(Title)
                .addGap(18, 18, 18)
                .addComponent(Description)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));

        LBL_Username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBL_Username.setForeground(new java.awt.Color(13, 56, 247));
        LBL_Username.setText("Username");

        TF_Username.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TF_Username.setForeground(new java.awt.Color(51, 51, 51));
        TF_Username.setBorder(null);
        TF_Username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_UsernameActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        LBL_Password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        LBL_Password.setForeground(new java.awt.Color(13, 56, 247));
        LBL_Password.setText("Password");

        PF_Password.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        PF_Password.setForeground(new java.awt.Color(51, 51, 51));
        PF_Password.setBorder(null);
        PF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_PasswordActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        BTN_SignIn.setBackground(new java.awt.Color(13, 56, 247));
        BTN_SignIn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        BTN_SignIn.setForeground(new java.awt.Color(255, 255, 255));
        BTN_SignIn.setText("Sign in");
        BTN_SignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SignInActionPerformed(evt);
            }
        });
        BTN_SignIn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BTN_SignInKeyPressed(evt);
            }
        });

        BTN_Close.setBackground(new java.awt.Color(255, 255, 255));
        BTN_Close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTN_Close.setForeground(new java.awt.Color(13, 56, 247));
        BTN_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/teacher/portal/images/Delete_20px.png"))); // NOI18N
        BTN_Close.setBorder(null);
        BTN_Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_CloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(TF_Username, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_Username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBL_Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PF_Password)
                    .addComponent(jSeparator2)
                    .addComponent(BTN_SignIn, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTN_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTN_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(LBL_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TF_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(LBL_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PF_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(BTN_SignIn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TF_UsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_UsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_UsernameActionPerformed

    private void PF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF_PasswordActionPerformed

    private void BTN_SignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SignInActionPerformed
     
        String username=TF_Username.getText();
        String password=new String (PF_Password.getPassword());
        admin = JDBC.isUser(username, password);
        if(admin != null){
           //JOptionPane.showMessageDialog(null, "Logged In Successfully!");
           
           
       
       
        new AdminMenuWindow().setVisible(true);
        this.dispose();
        
       }else{
            
            boolean flag = false;
            
            
            for(Student stu: Admin.getStudents())
            {
                if(stu.getUserId().equals(username) && stu.getPassword().equals(password))
                {
                    if(stu.getAccountStatus().equals("Active"))
                    {
                        new StudentMenuWindow(stu).setVisible(true);
                        flag = true;
                        this.dispose();
                        break;
                    }else{
                        JOptionPane.showMessageDialog(this, "Your account have been blocked ! \nPlease contact admin.");
                        flag = true;
                    }
                }
            }
            if(!flag)
            {
                for(Teacher teacher: Admin.getTeachers()){
                if(teacher.getUserId().equals(username) && teacher.getPassword().equals(password)){
                    new TeacherMenuWindow(teacher).setVisible(true);
                    flag = true;
                    this.dispose();
                   }
                }
            }
            if(!flag)
                JOptionPane.showMessageDialog(null, "Login Error !");
       }
       
        
    }//GEN-LAST:event_BTN_SignInActionPerformed

    private void BTN_CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_CloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTN_CloseActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        
    }//GEN-LAST:event_formKeyPressed

    private void BTN_SignInKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BTN_SignInKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_SignInKeyPressed

    public static Admin getAdmin() {
        return admin;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Close;
    private javax.swing.JButton BTN_SignIn;
    private javax.swing.JLabel Description;
    private javax.swing.JLabel Image;
    private javax.swing.JLabel LBL_Password;
    private javax.swing.JLabel LBL_Username;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JPasswordField PF_Password;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JTextField TF_Username;
    private javax.swing.JLabel Title;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
